project_name: GLSA-OVAL
#project_binary: glsa-oval
before:
  hooks:
    - go mod tidy
dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
  -
    env:
      - CGO_ENABLED=0
      binary: glsa-oval
    ldflags:
      - -s -w
      - -X "github.com/necrose99/GLSA-OVAL/cmd.CLIVersion={{ .Tag }}"
      - -X "github.com/necrose99/GLSA-OVAL/cmd.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
      - -X "github.com/necrose99/GLSA-OVAL/cmd.BuildCommit={{ .FullCommit }}"
    goos:
      - linux
      - windows
      # since on wifes laptop until i can replace mine , or desktops psu lightning is fun to even surge protectors :-( , i'm kinda hosed windows it is with wsl2 and a minimal linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: binary # this removes the tar of the archives, leaving the binaries alone
    name_template: glsa-oval-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'